import "server-only";
import { getAttemptService, getJournalService, listCodeFilesService, getAttemptFileService } from "@/services/attempt-service";
import { listBenchmarkCardsService } from "@/services/benchmark-service";
import { compareService } from "@/services/compare-service";
import { estimateTableService } from "@/services/estimate-service";
import { homeService } from "@/services/home-service";
import { listActiveJobsService, listBenchProcessesService, missingCapturesService } from "@/services/job-service";
import { leaderboardService, listModelsService, type LeaderboardSort } from "@/services/model-service";
import { getRunService, listRunDetailsService } from "@/services/run-service";
import type { AttemptRef } from "@/services/types/domain/attempt-types";
import type { BenchmarkGroup } from "@/services/types/domain/benchmark-types";
import { getVoteService } from "@/services/vote-service";
import { requestDal } from "./request";

export const homeDal = requestDal(() => homeService());
export const listModelsDal = requestDal(listModelsService);
export const leaderboardDal = requestDal((group?: BenchmarkGroup, sort?: LeaderboardSort) => leaderboardService({ group, sort }));
export const benchmarkCardsDal = requestDal((group?: BenchmarkGroup, query?: string) => listBenchmarkCardsService({ group, query }));
export const runDetailsDal = requestDal(listRunDetailsService);
export const runDal = requestDal((model: string, run: string) => getRunService({ model, run }));
export const attemptDal = requestDal((ref: AttemptRef) => getAttemptService(ref));
export const journalDal = requestDal((ref: AttemptRef) => getJournalService(ref));
export const codeFilesDal = requestDal((ref: AttemptRef) => listCodeFilesService(ref));
export const codeFileDal = requestDal((ref: AttemptRef, path: string) => getAttemptFileService({ ...ref, path }));
export const compareDal = requestDal((test: string, keys?: string[]) => compareService({ test, keys }));
export const voteDal = requestDal((test: string, candidates: string[]) => getVoteService({ test, candidates }));
export const estimateTableDal = requestDal((models: string[]) => estimateTableService(models));
export const activeJobsDal = requestDal(listActiveJobsService);
export const benchProcessesDal = requestDal(listBenchProcessesService);
export const missingCapturesDal = requestDal(missingCapturesService);
